DjangoUeditor/urls.py
#!/usr/bin/env python
# coding: utf-8

from django.conf.urls import patterns, url
from DjangoUeditor.views import UploadFile,ImageManager,RemoteCatchImage,SearchMovie,scrawlUp

urlpatterns = patterns('',
    url(r'^ImageUp/(?P<uploadpath>.*)', UploadFile, {'uploadtype':'image'}),
    url(r'^FileUp/(?P<uploadpath>.*)', UploadFile, {'uploadtype':'file'}),
    url(r'^scrawlUp/(?P<uploadpath>.*)$', scrawlUp),
    url(r'^ImageManager/(?P<imagepath>.*)$', ImageManager),
    url(r'^RemoteCatchImage/(?P<imagepath>.*)$', RemoteCatchImage),
    url(r'^SearchMovie/$', SearchMovie),
)
 

qipei/apps/product/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from qipei.apps.product.models import Sorts,Products
#from qipei.apps.store.models import Stores
from qipei.apps.account.models import Links
#from qipei.apps.store.forms import EditStoreForm, StoreAdForm
#from django.contrib.comments import Comment
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from django.core.urlresolvers import reverse_lazy





urlpatterns = patterns('qipei.apps.product',
    ## products
    url(r'^create$',
        CreateView.as_view(
            model=Products,
            template_name="create_product.html",
            success_url=reverse_lazy("list_product")
        ),
        name="create_product",
    ),
    url(r'^create/self$', 'views.create_product', name="create_self_product"),
    url(r'^list$', 'views.list_product', name="list_product"),
    # url(r'^update/(?P<pk>\d+)$',
    #     UpdateView.as_view(
    #         model = Products,
    #         template_name="update_product.html",
    #         success_url = reverse_lazy("manage_products")
    #         ),
    #     name="update_product"
    # ),
    url(r'^update/(?P<product_id>\d+)$','views.update_product', name="update_product",),

    #### 删除多个model
    url(r'^delete/(?P<product_id>\d+)$','views.delete_product', name="delete_product",),


    ## 分类
    url(r'^sort/list$','views.show_sort',name="list_sort"),
    url(r'^sort/create/(?P<parent>\w+)/$','views.add_sort',name="create_sort"),
    url(r'^sort/delete/(?P<pk>\d+)/$',
        DeleteView.as_view(
            model=Sorts,
            context_object_name="foo",
            template_name="confirm_delete.html",
            success_url=reverse_lazy("list_sort"),
        ),
        name="delete_sort",
     ),


    ## 友情链接
    url(r'^links/list$',
        ListView.as_view(
            queryset=Links.objects.all(),
            context_object_name="links",
            template_name="list_link.html",
        ),
        name='list_link'
    ),
    url(r'^links/create',
        CreateView.as_view(
            model=Links,
            template_name="create_link.html",
            success_url=reverse_lazy("list_link"),
        ),
        name='create_link'
    ),
    url(r'^links/delete/(?P<pk>\d+)/$',
        DeleteView.as_view(
            model=Links,
            context_object_name="foo",
            template_name="confirm_delete.html",
            success_url=reverse_lazy("list_link"),
        ),
        name="delete_link",
     ),
)

qipei/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

# from qipei

urlpatterns = patterns('',
    # url(r'^$', 'qipei.views.home', name='home'),
    # url(r'^qipei/', include('qipei.foo.urls')),
    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #search
    #(r'^search/', include('haystack.urls')),
    #需求相关url
    url(r'', include('qipei.apps.need.urls')),
    # accounts
    url(r'^accounts/', include("qipei.apps.account.urls")),
    # stores
    url(r'^store/', include("qipei.apps.store.urls")),
    # product
    url(r'^product/',include("qipei.apps.product.urls")),
    # custom
    url(r'^custom/',include("qipei.apps.custom.urls")),

    # forum
    url(r'^forum/',include("qipei.apps.forum.urls")),

    # welcome
    url(r'^wel/',include("qipei.apps.welcome.urls")),

    url(r'^$','qipei.apps.welcome.views.index'),
    # success page
    url(r'^ok',TemplateView.as_view(template_name="ok.html",),name='success'),

    url(r'^ueditor/', include('DjangoUeditor.urls')),

    url(r'', include('upload_avatar.urls')),

    url(r'^inbox/notifications/', include('notifications.urls')),



    # media managment
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qipei/apps/product/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-


from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel,TreeForeignKey

from DjangoUeditor.models import UEditorField

from qipei.settings import DOMAIN
from ..store.models import Stores


BOOLE_CHOICES=(
    ('是','1'),
    ('否','0'),
    )

#分类
class Sorts(MPTTModel):
    name=models.CharField(max_length=20,verbose_name="分类名称",unique=True)
    parent=TreeForeignKey("self", blank=True, null=True, related_name="children")


    def get_url(self):
        link='/wel/classfiy/'+  str(self.id) + '.html'
        return link

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name




#商品
class Products(models.Model):
    it_name=models.CharField(max_length=10,verbose_name='商品名称')

    company=models.ForeignKey(Stores,max_length=20,verbose_name='所属商铺',blank=True)

    sort=models.ManyToManyField(Sorts,verbose_name='分类')

    brand=models.CharField(max_length=10,verbose_name='品牌',blank=True)


    exit_date=models.DateField(verbose_name='上市时间',blank=True)

    price=models.CharField(max_length=20,verbose_name='价格')

    img=models.ImageField(verbose_name='商品图片',upload_to='image',blank=True)

    version=UEditorField(max_length=60,verbose_name='其他参数',
                         toolbars='list', blank=True)
    
    description=UEditorField(max_length=200,verbose_name='详细描述', toolbars='mini',
                             imagePath='product/img',filePath='product/file')


    def get_url(self):
        link=DOMAIN +'/store/'+  str(self.company.id) + '/view/' + str(self.id) + '.html'
        return link

    def img_url(self):

        if self.img:
            return self.img.url()
        else:
            default_img  = DOMAIN + "/static/img/defaultlogo.jpg"
            return default_img

    def __unicode__(self):
        return self.it_name



#留言
#class Messages(models.Model):
#    store=models.ForeignKey(Stores,verbose_name='商户名称',unique=True)
#    is_read=models.BooleanField(max_length='5',choices=BOOLE_CHOICES)
#    contact_number=models.DecimalField(max_digits='11',decimal_places='0',verbose_name='您的联系电话',blank=True)
#    content=models.CharField(max_length=200,verbose_name='留言内容')
#
#    def __unicode__(self):
#        return self.contact_number
#
## index ad*6
#class Ad_6(models.Model):
#    url1=models.URLField(verbose_name='图片链接1')
#    loc1=models.ImageField(verbose_name='首页小图1',upload_to="ad")
#
#    url2=models.URLField(verbose_name='图片链接2')
#    loc2=models.ImageField(verbose_name='首页小图2',upload_to="ad")
#
#    url3=models.URLField(verbose_name='图片链接3')
#    loc3=models.ImageField(verbose_name='首页小图3',upload_to="ad")
#
#    url4=models.URLField(verbose_name='图片链接4')
#    loc4=models.ImageField(verbose_name='首页小图4',upload_to="ad")
#
#    url5=models.URLField(verbose_name='图片链接5')
#    loc5=models.ImageField(verbose_name='首页小图5',upload_to="ad")
#
#    url6=models.URLField(verbose_name='图片链接6')
#    loc6=models.ImageField(verbose_name='首页小图6',upload_to="ad")
#
##index ad*3
#class Ad_middle(models.Model):
#    url1=models.URLField(verbose_name='图片链接1')
#    loc1=models.ImageField(verbose_name='首页中图1',upload_to="ad_middle")
#
#    url2=models.URLField(verbose_name='图片链接2')
#    loc2=models.ImageField(verbose_name='首页中图2',upload_to="ad_middle")
#
#    url3=models.URLField(verbose_name='图片链接3')
#    loc3=models.ImageField(verbose_name='首页中图3',upload_to="ad_middle")
#

#class News(models.Model):
#    title=models.CharField(max_length=20,verbose_name='标题')
#    content=models.CharField(max_length=500,verbose_name=' 内容 ')
#    store=models.ForeignKey(Stores)
#
#    def get_url(self):
#        link=DOMAIN +'/'+  str(self.store.id) + '/news/' + str(self.id) + '.html'
#        return link
#
#    def __unicode__(self):
#        return self.title

qipei/apps/product/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
#from django.http import HttpResponse
from django.forms import ModelForm,Textarea
from qipei.apps.product.models import Products, Sorts
from django.utils.translation import ugettext_lazy as _

class ProductsForm(ModelForm):
    class Meta:
        model=Products
        #        fields=('it_name','company','series','version','description','exit_date','price','img')
        widgets={
            'description':Textarea(attrs={'cols':10,'rows':10}),
            }

    def __init__(self, *args, **kwargs):

        super(ProductsForm, self).__init__(*args, **kwargs)


class ProductsStaffForm(ModelForm):
    class Meta:
        model=Products
        fields=('it_name','sort','brand','version','description','exit_date','price','img')
        widgets={
#            'company':HiddenInput,
            'description':Textarea(attrs={'cols':10,'rows':10}),
            }
#add store
#class StoreForm(ModelForm):
#    class Meta:
#        model=Stores
#        fields=('boss','name',)
#
#
##edit store
#class EditStoreForm(ModelForm):
#    class Meta:
#        fields=('name','tel','qq','address','notice','it_description')
#        model=Stores
#        widgets={
#            'notice':Textarea(attrs={'cols':10,'rows':10}),
#            'it_description':Textarea(attrs={'cols':10,'rows':10}),
#            }
#
##store ad
#class StoreAdForm(ModelForm):
#    class Meta:
#        fields=('logo','loc1','loc2','loc3')
#        model=Stores
#
#
#sort form
class SortForm(ModelForm):
    class Meta:
        model=Sorts


class AddForm(forms.Form):
    name = forms.CharField(label=_(u'名称'),max_length=10,widget=forms.TextInput(attrs={'size':10,}))

    def clean_name(self):
        '''验证重复分类'''
        name = Sorts.objects.filter(name__iexact=self.cleaned_data["name"])
        if not name:
            return self.cleaned_data["name"]
        raise forms.ValidationError(_(u"该项已经被使用请使用其他的"))
#
#
#
#class Ad6Form(ModelForm):
#    class Meta:
#        model=Ad_6
#
#class AdmiddleForm(ModelForm):
#    class Meta:
#        model=Ad_middle
#
#class LinkForm(ModelForm):
#    class Meta:
#        model=Links
#
#news
#class NewsForm(ModelForm):
#    class Meta:
#        felids=('title','content')
#        model = News
#        widgets={
#            'content':Textarea(attrs={'cols':10,'rows':10})
#        }

qipei/apps/product/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

from django.http import Http404
from django.template import RequestContext
from django.contrib.comments import Comment
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render_to_response, redirect, get_object_or_404

from .models import Sorts,Products
from .forms import  AddForm, ProductsStaffForm, ProductsForm
from ..account.tools import delete


##############################工具函数############################
#验证是否是正整数
def IsNUM(varObj):
    rule = '^\+?[1-9][0-9]*$'
    match = re.match( rule , varObj )
    if match:
        return True
    return False


##################################################################

#添加商品

@user_passes_test(lambda u: u.is_staff)
def create_product(request):
    user = request.user
    form = ProductsStaffForm()
    form['sort'].field.help_text ='<p class="alert alert-info">按下Ctrl键支持多选</p>'
    form['exit_date'].field.help_text ='<p class="alert alert-info">日期格式<strong><em>2012-12-21</em></strong></p>'
    product = Products()
    if request.method =='POST':
        form = ProductsStaffForm(request.POST,request.FILES)
        if form.is_valid():
            product = form.save(commit = False)
            product.company = user.stores
            product.save()
            #return reverse_lazy("list_product")
            return redirect(list_product)

    return  render_to_response('create_product.html',locals(),context_instance=RequestContext(request))


# 添加商品 
#def create_product(request):
#    """
#    商户添加商品
#    """
#    form = 


#管理商品
@user_passes_test(lambda u: u.is_staff)
def list_product(request):

    if request.user.is_superuser:
        products = Products.objects.all()
    elif request.user.is_staff:
        products = Products.objects.filter(company=request.user.stores)
    else:
        return HttpResponseRedirect(reverse("404"))

    return render_to_response("list_product.html",locals(),
                              context_instance=RequestContext(request))



@user_passes_test(lambda u: u.is_staff)
def update_product(request, product_id):

    """
    管理员删除任何商品
    商户删除自己的商品
    """

    product_instance = get_object_or_404(Products, id=product_id)

    if request.user.is_superuser or request.user == product_instance.company.boss_id:
        pass
    else:
        raise Http404

    form = ProductsForm(request.POST or None, instance=product_instance)

    if request.method == "POST":
        form = ProductsForm(request.POST.copy())
        if form.is_valid():
            form.save()

    return render_to_response('update_product.html', locals(),
                              context_instance=RequestContext(request))




@user_passes_test(lambda u: u.is_staff)
def delete_product(request, product_id):

    product = get_object_or_404(Products, id=product_id)

    if request.user.is_superuser:
        foo = product

    elif request.user.is_staff and product.company.boss == request.user:

        foo = product

    else:
        raise Http404

    return delete(request, foo, 'list_product')


#显示分类
@user_passes_test(lambda u: u.is_staff)
def show_sort(request):
    return render_to_response("list_sort.html",
        {'nodes':Sorts.objects.all()},
        context_instance=RequestContext(request))

#添加子分类
@user_passes_test(lambda u: u.is_staff)
def add_sort(request,parent):
    template_var={}
    form = AddForm()

    if request.method=="POST":
        form = AddForm(request.POST.copy())
        if form.is_valid():
            if parent!="root" and parent:
                sortname=form.cleaned_data['name']
                parent = Sorts.objects.get(id=parent)
                Sorts.objects.create(name=sortname,parent=parent,)
                return HttpResponseRedirect(reverse("list_sort"))

            elif parent == "root":
                sortname=form.cleaned_data['name']
                Sorts.objects.create(name=sortname)
                return HttpResponseRedirect(reverse("list_sort"))
            else:
                return HttpResponse('<script>alert("填写错误!");history.go(-1);</script>')
    template_var['par']=parent
    template_var['form']=form
    return  render_to_response("create_sort.html",template_var,context_instance=RequestContext(request))


#删除
@user_passes_test(lambda u: u.is_staff)
def dele(request, id, model):
    if IsNUM(id):
        p=model.objects.get(id=id)
        if p:
            p.delete()
        else:
            return HttpResponse('<script>alert("删除对象不存在");top.location="/accounts/index";</script>')
        return HttpResponse('<script>alert("删除成功");location.href=document.referrer;</script>')
    else:
        return HttpResponse('<script>alert("删除错误!");top.location="/accounts/index";</script>')


#messages
def comments(request):
    if request.user.is_superuser:
        comments=Comment.objects.all()
    elif request.user.is_staff:
        user_id=request.user.id
        comments=Comment.objects.filter(user=user_id)
    else:
        return HttpResponseRedirect(reverse("404"))
    template_var={
        'comments':comments,
    }
    return render_to_response('comments.html',template_var,context_instance=RequestContext(request))

qipei/apps/product/templates/create_link.html
{% extends "base-admin.html" %}
{% block title %}友情链接管理|添加{% endblock %}
{% block main %}
    <h3>友情链接管理&nbsp;|&nbsp;添加</h3>
    <hr>
    <h4>添加链接</h4>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <table border="0" cellpadding="0" >
            {{ form.as_p }}
        </table>
        <br>
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="添加"/>
            </div>
            <div class="btn-group">
                <a href="/goods/links/" class="btn">返回</a>
            </div>
    </form>
{% endblock %}

qipei/apps/product/templates/create_product.html
{% extends "base-admin.html" %}
{% block title %}添加商品{% endblock %}

{% block jq %}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
{% endblock %}

{% block head %}
{{ form.media }}
<link rel="stylesheet" href="/static/css/datetimepicker.css"/>
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/static/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>

{% endblock %}

{% block main %}
    <h2>添加商品</h2>
    <hr>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <table border="0" cellpadding="0" >
            {% include 'form_bootstrap.html' %}
        </table>
        <br>
        <div class="control-group" align="center">
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="添加"/>
            </div>
        </div>
    </form>

<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        language:  'zh-CN'
    });
</script>
{% endblock %}

qipei/apps/product/templates/create_sort.html
{% extends "base-admin.html" %}
{% block title %}添加分类{% endblock %}
{% block main %}
    <h3>添加分类</h3>
    <hr>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <table border="0" cellpadding="0" >
            {% if par != 'root' %}
                <p class="alert alert-success">为该分类添加子分类</p>
            {% else %}
                <p class="alert alert-success" >添加根分类</p>
            {% endif %}
            {{ form.as_p }}
            <p class="alert alert-info ">名称不得超过十个字节</p>
        </table>
        <br>
        <div class="control-group" align="center">
            <div class="btn-group">
                <a href="{% url 'list_sort' %}" class="btn btn-info">返回</a>
            </div>
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="添加"/>
            </div>
        </div>
    </form>

{% endblock %}

qipei/apps/product/templates/edititems.html
{% extends "base-admin.html" %}
{% block title %}修改商品信息{% endblock %}
{% block main %}
    <h3>修改商品信息</h3>
    <hr>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}


        <div class="control-group">
            <label class="control-label" for="id_it_name">商品名称</label>
            <div class="controls">
                <input id="id_it_name" maxlength="10" name="it_name" type="text" value="测试商品" />


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_company">所属商铺</label>
            <div class="controls">
                <select id="id_company" name="company">
                    {% for com in form.company.queryset.all %}
                        <option value="{{ com.id }}">{{ com.name }}</option>
                    {% endfor %}
                </select>



            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_sort">分类</label>
            <div class="controls">
                <select multiple="multiple" id="id_sort" name="sort">
                    <option value="1" selected="selected">ceshi</option>
                    <option value="2">nihao</option>
                </select>

                <span class="help-block"> 按下 &quot;Control&quot;，或者在Mac上按 &quot;Command&quot; 来选择多个值。</span>


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_brand">品牌</label>
            <div class="controls">
                <input id="id_brand" maxlength="10" name="brand" type="text" value="奥迪" />


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_version">其他参数</label>
            <div class="controls">
                <input id="id_version" maxlength="60" name="version" type="text" value="其他参数参数" />


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_description">描述</label>
            <div class="controls">
                <textarea cols="10" id="id_description" name="description" rows="10">
                    这就是描述</textarea>


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_exit_date">上市时间</label>
            <div class="controls">
                <input id="id_exit_date" name="exit_date" type="text" value="2012-12-21" />


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_price">价格</label>
            <div class="controls">
                <input id="id_price" maxlength="20" name="price" type="text" value="12312312312321312" />


            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_img">商品图片</label>
            <div class="controls">
                目前: <a href="/media/image/25012013064.jpg">image/25012013064.jpg</a> <input id="img-clear_id" name="img-clear" type="checkbox" /> <label for="img-clear_id">清除</label><br />修改: <input id="id_img" name="img" type="file" />


            </div>
        </div>





        <div class="control-group" align="center">
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="修改"/>
            </div>
        </div>
    </form>

{% endblock %}

qipei/apps/product/templates/edititems2.html
{% extends "base-admin.html" %}
{% block title %}修改商品信息{% endblock %}
{% block main %}
    <h3>修改商品信息</h3>
    <hr>
    <form action="" method="post"
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}

        {% for field in form %}
            <div class="control-group">
                <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="controls">
                    {{ field }}
                    {% if  field.help_text %}
                    <span class="help-block">{{ field.help_text }}</span>
                    {% endif %}
                    {% if  field.errors %}
                    <span class="help-block">{{ field.errors }}</span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <div class="control-group" align="center">
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="修改"/>
            </div>
        </div>
    </form>

{% endblock %}

qipei/apps/product/templates/list_link.html
{% extends "base-admin.html" %}
{% block title %}友情链接管理{% endblock %}
{% block main %}
    <h3>友情链接管理</h3>
    <hr>
    <div class="row">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>网站名称</th>
            <th>网站链接</th>
            <th>功能</th>
        </tr>
     </thead>
     <tbody>
        {% for link in links %}
            <tr>
				<th><a href={{ link.url }} target="_blank">{{ link.site }}</a></th>
                <th><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></th>
                <th><a href="{% url 'delete_link' link.id %}" class="btn btn-danger">删除</a></th>
            </tr>
        {% endfor %}
     </tbody>

    </table>

    </div>
    <hr>
	<a href="{% url 'create_link' %}" class="btn">添加链接</a>
{% endblock %}

qipei/apps/product/templates/list_product.html
{% extends "base-admin.html" %}
{% block title %}
    管理商品
{% endblock %}

{% load pagination_tags %}

{% block main %}
    <h2>商品管理</h2>
    <hr>
    <div>
        <div class="subnav">
            <ul class="nav nav-pills">
                <li>分类:</li>
                <li><a href="#" class="label active">全部</a></li>
                {% for sort in allsort %}
                    <li><a href="#" class="label">{{ sort }}</a></li>
                {% endfor %}
            </ul>
        </div>

    <hr>
	{% autopaginate products 10 %}
    <table class="table table-hover">
		<tr class="warning">
			<td>图片</td>
			<td>商品名</td>
			{% if user.is_superuser %}
			<td>所属商铺</td>
			{% elif user.is_staff %}
			<td>商品描述</td>
			{% endif %}
			<td>价格</td>
			<td>功能</td>
		</tr>
        {% for product in products %}
			<tr>
				<td width="40px">
					<a href="{{ product.get_url }}">
                        {% if product.img %}
						<img src="{{ product.img.url }}" alt="{{ item.it_name }}" width="30" height="30" />
                        {% else %}
						<img src="{{ product.img_url }}" alt="{{ item.it_name }}" width="30" height="30" />
                        {% endif %}
					</a>
				</td>
				<td width="150px">
					<a href="{{ product.get_url }}">{{ product.it_name }}</a>
				</td>
			<td width="100px">
			{% if user.is_superuser %}
				<a href="{{ product.company.get_url }}" class="label label-info">{{ product.company }}</a>
				{% elif user.is_staff %}
				<p class="alert alert-info">{{ product.description }}</p>
			{% endif %}
			</td>
				<td><span class="label label-important">{{ product.price }}</span>元</td>
				<td width="100px" align="center">
					<a href="{% url "update_product" product.id %}" class="btn-mini btn-primary">编辑</a>
					<a href="{% url "delete_product" product.id %}" class="btn-mini btn-danger" onClick="{if(confirm('确定要删除 『{{ product.it_name }} 』 吗?\n')){return true;}return false;}">删除</a>
				</td>
			</tr>
        {% endfor %}
    </table>
	{% paginate %}
    </div>
{% endblock %}

qipei/apps/product/templates/list_sort.html
{% extends "base-admin.html" %}
{% block title %}添加分类{% endblock %}
{% block main %}
    <div>
        <h3>全部分类</h3>
        <div>
            {% load mptt_tags %}
            <ul>
                {% recursetree nodes %}
                    <li class="category-list">
                        <a href="#" class="label label-success">{{ node.name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'create_sort' node.id %}" class="btn-mini btn-info">添加子分类</a>
                            <a href="{% url 'delete_sort' node.id %}" class="btn-mini btn-danger" >删除</a>
                        {% if not node.is_leaf_node %}
                            <ul class="children">
                                {{ children }}
                                <hr>
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
                <br>
                <a href="create/root/" class="btn btn-primary">添加根分类</a>
            </ul>
        </div>
    </div>
{% endblock %}

qipei/apps/product/templates/show_sort.html
{% extends "base-admin.html" %}
{% block title %}添加分类{% endblock %}
{% block main %}
    <div>
        <h3>全部分类</h3>
        <div>
            {% load mptt_tags %}
            <ul>
                {% recursetree nodes %}
                    <li class="category-list">
                        <a href="#" class="btn">{{ node.name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="add/{{ node.name }}/" class="btn-mini btn-info">添加子分类</a>
                            <a href="dele/{{ node.id }}/" class="btn-mini btn-danger" onClick="{if(confirm('确定要删除分类 『{{ node.name }}』 吗?\n')){return true;}return false;}">删除分类</a>
                        {% if not node.is_leaf_node %}
                            <ul class="children">
                                {{ children }}
                                <hr>
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
                <br>
                <a href="add/root/" class="btn btn-primary">添加根分类</a>
            </ul>
        </div>
    </div>
{% endblock %}

qipei/apps/product/templates/update_product.html
{% extends "base-admin.html" %}
{% block title %}修改商品信息{% endblock %}

{% block head %}
    {{ form.media }}
{% endblock %}

{% block main %}
    <h3>修改商品信息</h3>
    <hr>

    <form action="" method="post"
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}

        {% for field in form %}
            <div class="control-group">
                <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="controls">
                    {{ field }}
                    {% if  field.help_text %}
                        <span class="help-block">{{ field.help_text }}</span>
                    {% endif %}
                    {% if  field.errors %}
                        <span class="help-block">{{ field.errors }}</span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <div class="control-group" align="center">
            <div class="btn-group">
                <input type="submit"  class="btn btn-primary" value="修改"/>
            </div>
        </div>
    </form>


{% endblock %}